version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: garden
      POSTGRES_PASSWORD: garden
      POSTGRES_DB: garden
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - "${SERVER_PORT:-4000}:4000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    restart: unless-stopped
    depends_on:
      - server
    env_file: .env
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  pgdata:
